## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [1]:
import numpy as np
n=np.array([1,2,3,4,5])
m=np.array([0,1,2,3,4])
for i in n:
    if i==0:
        res="This array contains Zeros"
        break
    else:
        res="This array do not contains Zeros"
print(res)
for i in m:
    if i==0:
        res="This array contains Zeros"
        break
    else:
        res="This array do not contains Zeros"
print(res)

This array do not contains Zeros
This array contains Zeros


Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [2]:
a=np.append(np.zeros(10,dtype=int),np.ones(10,dtype=int))
a = np.append(a,[5]*10)
print(a)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [3]:
import numpy.random as random
x = random.normal(170,200,15)
print(x)

[-113.13260497  176.2149708   492.99659713  453.83902133  282.52520727
   39.0897881   228.407649    375.69246935    3.01418055  -19.68536107
  385.42912915   32.78415791  624.56815076  101.59807946  360.12806294]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [4]:
import numpy.random as random
x = random.normal(170,200,15)
print(x)

[ 137.10596778  163.46136442  525.44423792  347.60271133 -272.75591864
 -180.37701234  441.63816589  391.32224998  432.61922716  259.21273511
   97.32259441 -386.15646445  104.20138687   43.46958432  303.41555855]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [5]:
myarray = np.arange(1,17,1)
myarray=np.reshape(myarray,newshape=(4,4))
myarray[:,[0,-1]]=myarray[:,[-1,0]]
myarray[:,[1,2]]=myarray[:,[2,1]]
print(myarray)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [6]:
swapped = myarray[::-1,::-1]
print(swapped)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [7]:
a = np.arange(1,11,1)
b = np.arange(11,21,1)
print(a*b)

[ 11  24  39  56  75  96 119 144 171 200]


Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [8]:
arr = np.arange(2,11,1)
arr2 = arr.reshape(3,3)
print(arr2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [9]:
k = np.array(random.rand(27))
d = k.reshape(3,3,3)
print(d)

[[[0.75642555 0.2264326  0.3763617 ]
  [0.5573918  0.75856846 0.17910787]
  [0.63664316 0.17800467 0.81136929]]

 [[0.32526231 0.51365632 0.18090373]
  [0.44349641 0.18624646 0.96478257]
  [0.21667958 0.18473512 0.70628682]]

 [[0.31001494 0.96427668 0.63895835]
  [0.13239724 0.61118067 0.7169521 ]
  [0.93543594 0.15366665 0.82251363]]]


Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [10]:
rg = random.randint(100,size=(10))
print(rg)
print(np.max(rg),np.min(rg))

[64  4 44 42 89 78 13 49 33 68]
89 4


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [11]:
array1 = np.array([2.0, 3.0, 4.0, 5.0])
array2 = np.array([3.0, 6.0, 2.0, 20.0])
add_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2
divide_result = array1 / array2
print("Add:")
print(add_result)
print("Subtract:")
print(subtract_result)
print("Multiply:")
print(multiply_result)
print("Divide:")
print(divide_result)

Add:
[ 5.  9.  6. 25.]
Subtract:
[ -1.  -3.   2. -15.]
Multiply:
[  6.  18.   8. 100.]
Divide:
[0.66666667 0.5        2.         0.25      ]


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [12]:
a = np.array([0,1,2,3,4,5,6])
b = np.array([0,1,8,27,64,125,216])
print(a**b)

[         1          1        256 2030534587          0 1277562581
          0]


Problem 13: Create a Python project to guess a number that has randomly selected.

In [ ]:
n=np.random.randint(1,11)
s=int(input("Enter a random Number from 1 to 10:"))
if n==s:
      print("You Gussed the Correct Number")
else:
      print("you Guessed the wrong number. The random number is:"+str(n))

Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [ ]:
import numpy as np
rows, cols = 5, 5
array = np.zeros((rows, cols))
array[0, :] = 1  
array[-1, :] = 1 
array[:, 0] = 1  
array[:, -1] = 1 
print("array:")
print(array.astype(int))

Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [ ]:
arr=np.array([10,20,30])
arr2=np.array([40,50,60,70,80,90])
arr=np.append(arr,arr2)
print(arr)